### ISSUE TITLE
Potentially reduce image sizes by not installing recommended packages

### ISSUE THREAD

**Issue by achimnol** [lablup/sorna-repl#28]
`apt-get` has a cli argument ` --no-install-recommends` that skips installation of recommended packages but the main dependencies. This could reduce the kernel image sizes a lot.
Let's test this.

NOTE: Since we have basic unit tests for docker images, it would be sufficient to check if the tests are passed after building images after applying `--no-install-recommends`.

**Comment by GreatBean** [comment]
setup Ubuntu container on docker and install 'Python2.7' because Python3.* is default.
'--no-install-recommends' option makes little difference package installer.
![image](https://cloud.githubusercontent.com/assets/20082776/20293329/bd88e378-ab38-11e6-9682-06ed09ecc460.png)

two ubuntu container have different size. '341c7c34585d' container has recommend packages for python2.7.
